---

- hosts: homeserver
  become: true

  pre_tasks:

  - name: install updates (ubuntu)
    tags: always
    apt:
      update_cache: yes
    changed_when: false


  tasks:

  - name: disable dns server for pi-hole
    service:
      name: systemd-resolved
      state: stopped

  - name: change dns pointer
    lineinfile:
      path: /etc/resolv.conf
      regexp: '^nameserver 127'
      line: nameserver 1.1.1.1

  - name: install docker
    apt:
      name: 
        - docker.io
        - docker-compose
        - python3-pip
      state: latest

  - name: installs python docker sdk
    pip:
      name: docker
      state: latest

  - name: creates portainer container
    community.docker.docker_container:
      name: portainer
      image: portainer/portainer-ce:latest
      ports:
        - "9000:9000"
        - "8000:8000"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
        - portainer_data:/data
      restart_policy: always

  - name: copy over docker compose file for pihole
    copy:
      src: files/compose.yml
      dest: ~/compose.yml

  - name: run pihole container with compose
    community.docker.docker_compose:
      project_src: ~/
      state: present

